"""The renderer makes a complete recipe skill, and only from a good and accepted specification."""

import shutil

from helpers import FIXTURE, module, run

GOOD = FIXTURE / "good"
EXPECTED = FIXTURE / "good-rendered"
render = module("render")


def files_of(root):
    return {str(p.relative_to(root)): p.read_text() for p in sorted(root.rglob("*")) if p.is_file()}


def copy_with(tmp_path, old=None, new=None):
    target = tmp_path / "spec"
    shutil.copytree(GOOD, target)
    if old:
        text = (target / "spec.md").read_text()
        assert text.count(old) == 1
        (target / "spec.md").write_text(text.replace(old, new))
    return target


def test_rendering_the_fixture_gives_the_expected_files(tmp_path):
    code, out, _ = run("render", GOOD, "--commit", "0000000", "--out", tmp_path)
    assert code == 0
    assert files_of(tmp_path) == files_of(EXPECTED)
    assert sorted(files_of(tmp_path)) == [
        "docs/backups.md",
        "skills/backups/SKILL.md",
        "skills/backups/agent-templates/backups.md",
        "skills/backups/references/checklist.md",
    ]
    assert out.splitlines()[0] == "Rendered: docs/backups.md"


def test_each_rendered_file_has_the_stamp(tmp_path):
    run("render", GOOD, "--commit", "abc1234", "--branch", "901-other", "--out", tmp_path)
    for text in files_of(tmp_path).values():
        m = render.STAMP.search(text)
        assert m and m.group(1) == "901-other" and m.group(2) == "abc1234"
        assert "Do not edit this file." in text


def test_skill_file_obeys_the_rules_for_a_skill(tmp_path):
    run("render", GOOD, "--commit", "0000000", "--out", tmp_path)
    text = (tmp_path / "skills/backups/SKILL.md").read_text()
    assert text.startswith("---\nname: backups\ndescription: ")
    assert len(text.splitlines()) < 500
    assert "## Risk analysis" in text and "`regulatory`" in text
    assert ".agents/kit/backups.md" in text
    # The recipe names no source and copies no source text.
    assert "S-01" not in text and "standards.example" not in text


def test_checklist_reference_has_no_source_and_no_item_that_is_not_admitted(tmp_path):
    run("render", GOOD, "--commit", "0000000", "--out", tmp_path)
    text = (tmp_path / "skills/backups/references/checklist.md").read_text()
    assert "| Id | Item | Risk that it answers | Level | Check |" in text
    assert "C-04" not in text and "S-0" not in text
    ids = [line.split("|")[1].strip() for line in text.splitlines() if line.startswith("| C-")]
    assert ids == ["C-01", "C-05", "C-02", "C-03"]


def test_nothing_is_rendered_without_the_acceptance(tmp_path):
    spec = copy_with(tmp_path, "**Accepted**: A. Person, 2026-01-15", "**Accepted**: pending")
    out_dir = tmp_path / "out"
    code, out, _ = run("render", spec, "--commit", "0000000", "--out", out_dir)
    assert code == 1 and "the owner did not accept" in out
    assert not out_dir.exists()


def test_nothing_is_rendered_when_the_check_fails(tmp_path):
    spec = copy_with(tmp_path, "| S-02 section 4 |", "| S-09 section 4 |")
    out_dir = tmp_path / "out"
    code, out, _ = run("render", spec, "--commit", "0000000", "--out", out_dir)
    assert code == 1 and "the check of the specification fails" in out
    assert not out_dir.exists()


def test_target_folder_of_section_5(tmp_path):
    spec = copy_with(
        tmp_path,
        "- **Goal**: Each record",
        "- **Target folder**: `factory/example/`\n- **Goal**: Each record",
    )
    out_dir = tmp_path / "out"
    code, _, _ = run("render", spec, "--commit", "0000000", "--out", out_dir)
    assert code == 0
    assert (out_dir / "factory/example/SKILL.md").is_file()
    assert (out_dir / "docs/backups.md").is_file()
    assert not (out_dir / "skills").exists()


def test_check_finds_a_skill_that_is_not_fresh(tmp_path):
    spec = copy_with(tmp_path)
    out_dir = tmp_path / "out"
    run("render", spec, "--commit", "abc1234", "--out", out_dir)
    # The commit and the branch come from the stamp on disk.
    code, out, _ = run("render", spec, "--check", "--out", out_dir)
    assert code == 0 and "the same as a fresh rendering" in out
    text = (spec / "spec.md").read_text().replace("not by hand.", "not by a person.")
    (spec / "spec.md").write_text(text)
    code, out, _ = run("render", spec, "--check", "--out", out_dir)
    assert code == 1
    assert "skills/backups/references/checklist.md" in out
    run("render", spec, "--commit", "abc1235", "--out", out_dir)
    assert run("render", spec, "--check", "--out", out_dir)[0] == 0


def test_check_writes_nothing(tmp_path):
    out_dir = tmp_path / "out"
    code, out, _ = run("render", GOOD, "--check", "--commit", "0000000", "--out", out_dir)
    assert code == 1 and "differs" in out and not out_dir.exists()


def test_a_product_word_stops_the_rendering(tmp_path):
    words = tmp_path / "words.txt"
    words.write_text("restore\n")
    out_dir = tmp_path / "out"
    code, out, _ = run("render", GOOD, "--commit", "0000000", "--out", out_dir, "--words", words)
    assert code == 1 and "product word 'restore'" in out and not out_dir.exists()


def test_commit_is_necessary(tmp_path):
    code, out, _ = run("render", GOOD, "--out", tmp_path)
    assert code == 1 and "--commit" in out


def test_two_runs_give_the_same_bytes(tmp_path):
    run("render", GOOD, "--commit", "0000000", "--out", tmp_path / "a")
    run("render", GOOD, "--commit", "0000000", "--out", tmp_path / "b")
    assert files_of(tmp_path / "a") == files_of(tmp_path / "b")


def test_input_that_cannot_be_read(tmp_path):
    code, _, err = run("render", tmp_path, "--commit", "0000000")
    assert code == 2 and "cannot be read" in err
